package com.dingyl.wanandroid.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dingyl.wanandroid.data.BannerDataBean;
import com.dingyl.wanandroid.data.HomeDataBean;

import com.dingyl.wanandroid.greendao.BannerDataBeanDao;
import com.dingyl.wanandroid.greendao.HomeDataBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bannerDataBeanDaoConfig;
    private final DaoConfig homeDataBeanDaoConfig;

    private final BannerDataBeanDao bannerDataBeanDao;
    private final HomeDataBeanDao homeDataBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bannerDataBeanDaoConfig = daoConfigMap.get(BannerDataBeanDao.class).clone();
        bannerDataBeanDaoConfig.initIdentityScope(type);

        homeDataBeanDaoConfig = daoConfigMap.get(HomeDataBeanDao.class).clone();
        homeDataBeanDaoConfig.initIdentityScope(type);

        bannerDataBeanDao = new BannerDataBeanDao(bannerDataBeanDaoConfig, this);
        homeDataBeanDao = new HomeDataBeanDao(homeDataBeanDaoConfig, this);

        registerDao(BannerDataBean.class, bannerDataBeanDao);
        registerDao(HomeDataBean.class, homeDataBeanDao);
    }
    
    public void clear() {
        bannerDataBeanDaoConfig.clearIdentityScope();
        homeDataBeanDaoConfig.clearIdentityScope();
    }

    public BannerDataBeanDao getBannerDataBeanDao() {
        return bannerDataBeanDao;
    }

    public HomeDataBeanDao getHomeDataBeanDao() {
        return homeDataBeanDao;
    }

}
