package com.dingyl.wanandroid.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dingyl.wanandroid.data.HomeDataDaoBean;

import com.dingyl.wanandroid.greendao.HomeDataDaoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeDataDaoBeanDaoConfig;

    private final HomeDataDaoBeanDao homeDataDaoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeDataDaoBeanDaoConfig = daoConfigMap.get(HomeDataDaoBeanDao.class).clone();
        homeDataDaoBeanDaoConfig.initIdentityScope(type);

        homeDataDaoBeanDao = new HomeDataDaoBeanDao(homeDataDaoBeanDaoConfig, this);

        registerDao(HomeDataDaoBean.class, homeDataDaoBeanDao);
    }
    
    public void clear() {
        homeDataDaoBeanDaoConfig.clearIdentityScope();
    }

    public HomeDataDaoBeanDao getHomeDataDaoBeanDao() {
        return homeDataDaoBeanDao;
    }

}
