package com.dingyl.wanandroid.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dingyl.wanandroid.helper.StringConverter;
import java.util.List;

import com.dingyl.wanandroid.data.HomeDataBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOME_DATA_BEAN".
*/
public class HomeDataBeanDao extends AbstractDao<HomeDataBean, Void> {

    public static final String TABLENAME = "HOME_DATA_BEAN";

    /**
     * Properties of entity HomeDataBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ApkLink = new Property(0, String.class, "apkLink", false, "APK_LINK");
        public final static Property Author = new Property(1, String.class, "author", false, "AUTHOR");
        public final static Property ChapterId = new Property(2, int.class, "chapterId", false, "CHAPTER_ID");
        public final static Property ChapterName = new Property(3, String.class, "chapterName", false, "CHAPTER_NAME");
        public final static Property Collect = new Property(4, boolean.class, "collect", false, "COLLECT");
        public final static Property CourseId = new Property(5, int.class, "courseId", false, "COURSE_ID");
        public final static Property Desc = new Property(6, String.class, "desc", false, "DESC");
        public final static Property EnvelopePic = new Property(7, String.class, "envelopePic", false, "ENVELOPE_PIC");
        public final static Property Fresh = new Property(8, boolean.class, "fresh", false, "FRESH");
        public final static Property AnotherId = new Property(9, int.class, "anotherId", false, "ANOTHER_ID");
        public final static Property Link = new Property(10, String.class, "link", false, "LINK");
        public final static Property NiceDate = new Property(11, String.class, "niceDate", false, "NICE_DATE");
        public final static Property Origin = new Property(12, String.class, "origin", false, "ORIGIN");
        public final static Property ProjectLink = new Property(13, String.class, "projectLink", false, "PROJECT_LINK");
        public final static Property PublishTime = new Property(14, long.class, "publishTime", false, "PUBLISH_TIME");
        public final static Property SuperChapterId = new Property(15, int.class, "superChapterId", false, "SUPER_CHAPTER_ID");
        public final static Property SuperChapterName = new Property(16, String.class, "superChapterName", false, "SUPER_CHAPTER_NAME");
        public final static Property Tags = new Property(17, String.class, "tags", false, "TAGS");
        public final static Property Title = new Property(18, String.class, "title", false, "TITLE");
        public final static Property Type = new Property(19, int.class, "type", false, "TYPE");
        public final static Property UserId = new Property(20, int.class, "userId", false, "USER_ID");
        public final static Property Visible = new Property(21, int.class, "visible", false, "VISIBLE");
        public final static Property Zan = new Property(22, int.class, "zan", false, "ZAN");
    }

    private final StringConverter tagsConverter = new StringConverter();

    public HomeDataBeanDao(DaoConfig config) {
        super(config);
    }
    
    public HomeDataBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOME_DATA_BEAN\" (" + //
                "\"APK_LINK\" TEXT," + // 0: apkLink
                "\"AUTHOR\" TEXT," + // 1: author
                "\"CHAPTER_ID\" INTEGER NOT NULL ," + // 2: chapterId
                "\"CHAPTER_NAME\" TEXT," + // 3: chapterName
                "\"COLLECT\" INTEGER NOT NULL ," + // 4: collect
                "\"COURSE_ID\" INTEGER NOT NULL ," + // 5: courseId
                "\"DESC\" TEXT," + // 6: desc
                "\"ENVELOPE_PIC\" TEXT," + // 7: envelopePic
                "\"FRESH\" INTEGER NOT NULL ," + // 8: fresh
                "\"ANOTHER_ID\" INTEGER NOT NULL ," + // 9: anotherId
                "\"LINK\" TEXT," + // 10: link
                "\"NICE_DATE\" TEXT," + // 11: niceDate
                "\"ORIGIN\" TEXT," + // 12: origin
                "\"PROJECT_LINK\" TEXT," + // 13: projectLink
                "\"PUBLISH_TIME\" INTEGER NOT NULL ," + // 14: publishTime
                "\"SUPER_CHAPTER_ID\" INTEGER NOT NULL ," + // 15: superChapterId
                "\"SUPER_CHAPTER_NAME\" TEXT," + // 16: superChapterName
                "\"TAGS\" TEXT," + // 17: tags
                "\"TITLE\" TEXT," + // 18: title
                "\"TYPE\" INTEGER NOT NULL ," + // 19: type
                "\"USER_ID\" INTEGER NOT NULL ," + // 20: userId
                "\"VISIBLE\" INTEGER NOT NULL ," + // 21: visible
                "\"ZAN\" INTEGER NOT NULL );"); // 22: zan
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOME_DATA_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HomeDataBean entity) {
        stmt.clearBindings();
 
        String apkLink = entity.getApkLink();
        if (apkLink != null) {
            stmt.bindString(1, apkLink);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(2, author);
        }
        stmt.bindLong(3, entity.getChapterId());
 
        String chapterName = entity.getChapterName();
        if (chapterName != null) {
            stmt.bindString(4, chapterName);
        }
        stmt.bindLong(5, entity.getCollect() ? 1L: 0L);
        stmt.bindLong(6, entity.getCourseId());
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(7, desc);
        }
 
        String envelopePic = entity.getEnvelopePic();
        if (envelopePic != null) {
            stmt.bindString(8, envelopePic);
        }
        stmt.bindLong(9, entity.getFresh() ? 1L: 0L);
        stmt.bindLong(10, entity.getAnotherId());
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(11, link);
        }
 
        String niceDate = entity.getNiceDate();
        if (niceDate != null) {
            stmt.bindString(12, niceDate);
        }
 
        String origin = entity.getOrigin();
        if (origin != null) {
            stmt.bindString(13, origin);
        }
 
        String projectLink = entity.getProjectLink();
        if (projectLink != null) {
            stmt.bindString(14, projectLink);
        }
        stmt.bindLong(15, entity.getPublishTime());
        stmt.bindLong(16, entity.getSuperChapterId());
 
        String superChapterName = entity.getSuperChapterName();
        if (superChapterName != null) {
            stmt.bindString(17, superChapterName);
        }
 
        List tags = entity.getTags();
        if (tags != null) {
            stmt.bindString(18, tagsConverter.convertToDatabaseValue(tags));
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(19, title);
        }
        stmt.bindLong(20, entity.getType());
        stmt.bindLong(21, entity.getUserId());
        stmt.bindLong(22, entity.getVisible());
        stmt.bindLong(23, entity.getZan());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HomeDataBean entity) {
        stmt.clearBindings();
 
        String apkLink = entity.getApkLink();
        if (apkLink != null) {
            stmt.bindString(1, apkLink);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(2, author);
        }
        stmt.bindLong(3, entity.getChapterId());
 
        String chapterName = entity.getChapterName();
        if (chapterName != null) {
            stmt.bindString(4, chapterName);
        }
        stmt.bindLong(5, entity.getCollect() ? 1L: 0L);
        stmt.bindLong(6, entity.getCourseId());
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(7, desc);
        }
 
        String envelopePic = entity.getEnvelopePic();
        if (envelopePic != null) {
            stmt.bindString(8, envelopePic);
        }
        stmt.bindLong(9, entity.getFresh() ? 1L: 0L);
        stmt.bindLong(10, entity.getAnotherId());
 
        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(11, link);
        }
 
        String niceDate = entity.getNiceDate();
        if (niceDate != null) {
            stmt.bindString(12, niceDate);
        }
 
        String origin = entity.getOrigin();
        if (origin != null) {
            stmt.bindString(13, origin);
        }
 
        String projectLink = entity.getProjectLink();
        if (projectLink != null) {
            stmt.bindString(14, projectLink);
        }
        stmt.bindLong(15, entity.getPublishTime());
        stmt.bindLong(16, entity.getSuperChapterId());
 
        String superChapterName = entity.getSuperChapterName();
        if (superChapterName != null) {
            stmt.bindString(17, superChapterName);
        }
 
        List tags = entity.getTags();
        if (tags != null) {
            stmt.bindString(18, tagsConverter.convertToDatabaseValue(tags));
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(19, title);
        }
        stmt.bindLong(20, entity.getType());
        stmt.bindLong(21, entity.getUserId());
        stmt.bindLong(22, entity.getVisible());
        stmt.bindLong(23, entity.getZan());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public HomeDataBean readEntity(Cursor cursor, int offset) {
        HomeDataBean entity = new HomeDataBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // apkLink
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // author
            cursor.getInt(offset + 2), // chapterId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // chapterName
            cursor.getShort(offset + 4) != 0, // collect
            cursor.getInt(offset + 5), // courseId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // desc
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // envelopePic
            cursor.getShort(offset + 8) != 0, // fresh
            cursor.getInt(offset + 9), // anotherId
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // link
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // niceDate
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // origin
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // projectLink
            cursor.getLong(offset + 14), // publishTime
            cursor.getInt(offset + 15), // superChapterId
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // superChapterName
            cursor.isNull(offset + 17) ? null : tagsConverter.convertToEntityProperty(cursor.getString(offset + 17)), // tags
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // title
            cursor.getInt(offset + 19), // type
            cursor.getInt(offset + 20), // userId
            cursor.getInt(offset + 21), // visible
            cursor.getInt(offset + 22) // zan
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HomeDataBean entity, int offset) {
        entity.setApkLink(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setAuthor(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setChapterId(cursor.getInt(offset + 2));
        entity.setChapterName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCollect(cursor.getShort(offset + 4) != 0);
        entity.setCourseId(cursor.getInt(offset + 5));
        entity.setDesc(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setEnvelopePic(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setFresh(cursor.getShort(offset + 8) != 0);
        entity.setAnotherId(cursor.getInt(offset + 9));
        entity.setLink(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setNiceDate(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setOrigin(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setProjectLink(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setPublishTime(cursor.getLong(offset + 14));
        entity.setSuperChapterId(cursor.getInt(offset + 15));
        entity.setSuperChapterName(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setTags(cursor.isNull(offset + 17) ? null : tagsConverter.convertToEntityProperty(cursor.getString(offset + 17)));
        entity.setTitle(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setType(cursor.getInt(offset + 19));
        entity.setUserId(cursor.getInt(offset + 20));
        entity.setVisible(cursor.getInt(offset + 21));
        entity.setZan(cursor.getInt(offset + 22));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(HomeDataBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(HomeDataBean entity) {
        return null;
    }

    @Override
    public boolean hasKey(HomeDataBean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
